### ISSUE TITLE
pi-aREST to set relay ON and OFF

### ISSUE THREAD

**Issue by hemantkamalakar** [marcoschwartz/pi-aREST#1]
Hello,
I have installed pi-aREST on my Raspberry Pi ver B.
When I access the web application on port 3000 I am getting the response from pi-aREST. 
But when I try to set a pin to HIGH for a relay It sets the Relay to ON state and immediately sets it to OFF state.
Could you please let me know if i am missing something?

Regards,
Hemant

**Comment by marcoschwartz** [comment]
Hello Hemant,

I will test that tomorrow and let you know if I can reproduce the error. Thanks for noticing!

**Comment by marcoschwartz** [comment]
That's now fixed :)
