### ISSUE TITLE
npm install is not working properly

### ISSUE THREAD

**Issue by starbuck93** [marcoschwartz/pi-aREST#2]
Here is the console log from the command: http://pastebin.com/CRKpxbh3
I installed nodejs and npm like this: `sudo apt-get install nodejs npm node-semver` [from this stack exchange](http://raspberrypi.stackexchange.com/questions/4194/getting-npm-installed-on-raspberry-pi-wheezy-image)

**Comment by marcoschwartz** [comment]
The issue is inside the log :) See this:

npm WARN This failure might be due to the use of legacy binary "node"

Please make sure you install the latest version of Node.js with:

https://learn.adafruit.com/node-embedded-development/installing-node-dot-js
