### ISSUE TITLE
Trying to read state of pin toggles the current state

### ISSUE THREAD

**Issue by marauderlabs** [marcoschwartz/pi-aREST#3]
`/digital/8` or `/digital/8/r` toggles the pin state. 

I'm trying this locally without the connection to the cloud enabled.

Detail:
1. 
With relay off, the request `/digital/3/r` returns the following and the relay turns on.
`{"id":"xyz","name":"devname","hardware":"rpi","connected":true,"message":"Pin 3 set to r"}`

2.
With relay on, the request `/digital/3/` returns the following and the relay turns off. `{"id":"xyz","name":"devname","hardware":"rpi","connected":true,"return_value":true}`

**Comment by marcoschwartz** [comment]
Hello, that's now fixed :) It was a bug of the GPIO library, I now switched the whole project to rpio (https://github.com/jperkin/node-rpio) which is much more reliable. This will also allow me to implement hardware PWM in the future.
