### ISSUE TITLE
A digital get request forces gpio to input mode

### ISSUE THREAD

**Issue by Julusian** [marcoschwartz/pi-aREST#4]
Calling /digital/2/0 correctly sets pin 2 to output mode and sets it low.
Following this with a /digitial/2 causes the mode to be set to input mode, causing the pin to then go high as that is the default state of the pin.
This is causing the [home assistant integration](https://home-assistant.io/components/switch.arest/) to not work with gpio as it polls the get endpoint to keep in sync.

By making this modification:
```
app.get('/:command/:pin', function(req, res){

      if (req.params.command == 'digital') {

        console.log("PRE: ", rpio.read(parseInt(req.params.pin)));

        // Read
        rpio.open(parseInt(req.params.pin), rpio.INPUT);
        value = rpio.read(parseInt(req.params.pin));
        console.log("POST: ", value);
```
and calling /digital/2, i get the following on the console, showing it is the pin open causing the issue.
```
PRE:  0
POST:  1
```

**Comment by marcoschwartz** [comment]
Hey! Thanks for sending the issue, that's a case I didn't think about :) So you mean the library would have to store the state of the pin in case it has been set to an output before?
