### ISSUE TITLE
Raspberry Pi 3 Model B supported?

### ISSUE THREAD

**Issue by lesliechw** [marcoschwartz/pi-aREST#5]
I setup aREST Pi on RPi 3 Model B.

The REST call respond fine BUT, the GPIO state doesn't change at all.

Is RPi 3 not supported?

Or is there anything else I need to set?

**Comment by lesliedoghouse** [comment]
Tested with RPi 1, the result is the same. What is the possible area goes wrong? Please advice.

**Comment by marcoschwartz** [comment]
Hi, just tested on my Raspberry Pi 3, works fine :) 

Make sure to install the module with --unsafe-perm option, I updated the README to reflect that.

Let me know if that helps!

**Comment by marcoschwartz** [comment]
Also check that you are using the correct pin mapping, by default it follows the GPIO numbers and not the logical pin numbers

**Comment by lesliechw** [comment]
Ok will retry. Thanks.
