### ISSUE TITLE
functions not working

### ISSUE THREAD

**Issue by treii28** [marcoschwartz/pi-aREST#6]
I installed the node pi-aRest and regardless of what I try (including the style represented in the basic example) I cannot seem to get a function to work properly. If I use the syntax shown in the example I get 'callback is not a function'.  If I remove 'callback' from the second parameter, it just sits there and does nothing.

What I need to do is to have various functions return custom json data, such as reading from a multi-entry log json file. I've already worked out the code to read the file with fs and parse it. I just need to know how to assign an end point so when I ask for 'http://localhost:3000/userdata' it will return the array of json style log entries back.

```
// Include modules
var fs = require('fs');
var express = require('express');
var app = express();
var piREST = require('pi-arest')(app);


// ID & name
piREST.set_id('34f5eQ');
piREST.set_name('my_new_Pi');

// tried this with and without a 'input' and 'callback' placeholder
function getUserData() {
  var userdata = fs.readFileSync('userdata.json');
  var userLog = JSON.parse(userdata);
  return userLog;
};

piREST.function('getdata',getUserData);

// Start server
var server = app.listen(3000, function() {
    console.log('Listening on port %d', server.address().port);
});

```

**Comment by marcoschwartz** [comment]
Hi! Just tested the code on my own Pi, I think the problem is in the definition of your function. You need to make sure to include a callback or it won't work, as the code of pi-arest is async. I invite you to check the basic.js example in the folder. Let me know if that works!
