### ISSUE TITLE
Pi-aREST for win iot

### ISSUE THREAD

**Issue by fastlater** [marcoschwartz/pi-aREST#7]
Simple question. Can I use this library on the raspberry pi with win 10 iot os installed?

**Comment by marcoschwartz** [comment]
Hi,

Sure thing, I only tested it on Raspbian but it should work on every OS where you can execute Node.js. You can read more here: https://audministrator.wordpress.com/2018/01/15/windows-core-iot-nodejs-on-a-raspberry-pi3/
