### ISSUE TITLE
Device not shown in Dashboard

### ISSUE THREAD

**Issue by xXMrJackXx** [marcoschwartz/pi-aREST#9]
Hi,

I use the pi-aREST library with the following code (snippet):
```javascript
var piREST = require('pi-arest')(app);

piREST.set_id('xxxx');
piREST.set_name('testXxxx');

piREST.connect();

piREST.publish('temp', _temp);
```

My device gets correctly connected to the cloud since I get a response when calling https://cloud.arest.io/xxxx/temp

But the device doesn't show up in my Dashboard and I have no idea how to link my device to my account.
In the library I see no possibility to set the API key from the accounts page.

How can I make my device visible in my dashboard?
Thanks

**Comment by marcoschwartz** [comment]
Hello, sorry for the late answer to this issue! We make a lot of changes to the API & to the dashboard since then, please follow our official quick start guide to solve your issue: https://arest.io/quick-start
